src/Entity/Cart.php
<?php

namespace App\Entity;

class Cart
{

    private $items = [];

    public function add($product)
    {
        $index = $product->getIdProduct();

        if (array_key_exists($index, $this->items)) {
            $purchase = $this->items[$product->getIdProduct()];

            $newQuantity = $purchase->getQuantity();
            $newQuantity++;

            $purchase->setQuantity($newQuantity);
            $this->items[$index] = $purchase;
        } else {
            $purchase = new Purchase($product);
            $this->items[$product->getIdProduct()] = $purchase;
        }
    }

    public function update($modifications)
    {
        if (count($this->items) > 0) {
            $newQuantities = $modifications["txtQuantity"];

            foreach ($this->items as $key => $item) {
                $newQuantity = $newQuantities[$key];
                
                if ($newQuantity >= 0 && $newQuantity <= 99 && is_numeric($newQuantity)) {
                    if ($newQuantity == 0) {
                        $this->delete($key);
                    } else {
                        $item->setQuantity($newQuantity);
                    }
                }
            }
        }
    }


    public function delete($index)
    {
        if (array_key_exists($index, $this->items)) {
            unset($this->items[$index]);
        }
    }

    public function getItems()
    {
        return $this->items;
    }

    public function getSubtotal(){
        return $this->calculatePricing();
    }

    public function getTps() {
        return $this->calculatePricing(Constants::TPS);
    }

    public function getTvq() {
        return $this->calculatePricing(Constants::TVQ);
    }

    public function getDeliveryFee(){
        return count($this->items) > 0 ? Constants::DELIVERY_FEE : 0;
    }

    public function getTotal() {

        $total = $this->getSubtotal();
        $total += $this->getTps();
        $total += $this->getTvq();
        $total += $this->getDeliveryFee();

        return $total;
    }

    public function getStripePriceInCents() {

        // get price without taxes
        $total = $this->getTotal() * 100;
        return round($total, 0, PHP_ROUND_HALF_UP);
    }

    private function calculatePricing($target = null){
        $total = 0;

        if (count($this->items) > 0){
            foreach ($this->items as $item) {
                $total += ($item->getPrice() * $item->getQuantity());
            }
        }

        return $target != null ? $total * $target : $total;
    }

    public function isEmpty() {
        if (count($this->items) === 0) {
            return true;
        }
        return false;
    }
}

src/Controller/CheckOutController.php
<?php

namespace App\Controller;

use App\Core\Icons;
use App\Core\Notification;
use App\Core\NotificationColor;
use App\Entity\Constants;
use App\Entity\Order;
use Doctrine\ORM\EntityManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\Routing\Annotation\Route;
use Stripe;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class CheckOutController extends AbstractController
{
    private $em = null;

    public function __construct(ManagerRegistry $doctrine)
    {
        $this->em = $doctrine->getManager();
    }

    #[Route('/orders/review', name: 'route_orderReview')]
    public function orderReview(Request $request): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $user = $this->getUser();
        $cart = $request->getSession()->get('cart');

        //Reglé dans une issue précédente
        if ($cart != null && !$cart->isEmpty()) {

            return $this->render('checkout/orderReview.html.twig', [
                'cart' => $cart,
                'user' => $user
            ]);
        }

        return $this->redirectToRoute('route_cart');
    }

    #[Route('/stripe-chechout', name: 'stripe_chechout')]
    public function stripeCheckout(Request $request): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $user = $this->getUser();
        $cart = $request->getSession()->get('cart');

        \Stripe\Stripe::setApiKey($_ENV["STRIPE_SECRET"]);

        $successURL = $this->generateUrl('stripe_success', [], UrlGeneratorInterface::ABSOLUTE_URL) . "?stripe_id={CHECKOUT_SESSION_ID}";

        $sessionData = [
            'line_items' => [[
                'quantity' => 1,
                'price_data' => ['unit_amount' => $cart->getStripePriceInCents(), 'currency' => 'CAD', 'product_data' => ['name' => 'Dark Roasted Coffee checkout']]
            ]],
            'customer_email' => $user->getEmail(),
            'payment_method_types' => ['card'],
            'mode' => 'payment',
            'success_url' => $successURL,
            'cancel_url' => $this->generateUrl('stripe_cancel', [], UrlGeneratorInterface::ABSOLUTE_URL)
        ];

        $checkoutSession = \Stripe\Checkout\Session::create($sessionData);
        return $this->redirect($checkoutSession->url, 303);
    }

    #[Route('/stripe-success', name: 'stripe_success')]
    public function stripeSuccess(Request $request): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $user = $this->getUser();
        $cart = $request->getSession()->get('cart');

        try {
            $stripe = new \Stripe\StripeClient($_ENV["STRIPE_SECRET"]);

            $stripeSessionId = $request->query->get('stripe_id');
            $sessionStripe = $stripe->checkout->sessions->retrieve($stripeSessionId);
            $payementIntent = $sessionStripe->payment_intent;

            $order = new Order($user, $payementIntent);
            
            $itemsOutOfStock = [];

            foreach ($cart->getItems() as $item) {

                $entity = $this->em->merge($item);
                $order->addProduct($entity);

                $entity->decrementQuantityInStock();

                if ($entity->getQuantityInStock() <= 0) {
                    array_push($itemsOutOfStock, $entity);
                }
            }

            $this->em->persist($order);
            $this->em->flush();

            $notification = Notification::createOutOfStockNotification($order->getIdOrder(), $itemsOutOfStock);
            $this->addFlash("order", $notification);

            $request->getSession()->remove('cart');

        } catch (\Exception $e) {
            return $this->redirectToRoute('route_catalogue');
        }

        return $this->redirectToRoute('route_userOrders');
    }

    #[Route('/stripe-cancel', name: 'stripe_cancel')]
    public function stripeCancel(): Response
    {
        $this->addFlash("order", new Notification("WARNING", "Transaction failed, please retry.", NotificationColor::DANGER, Icons::WARNING));

        return $this->redirectToRoute('route_cart');
    }

    #[Route('/user/orders', name: 'route_userOrders')]
    public function userOrders(Request $request): Response
    { 
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $user = $this->getUser();
        $orders = $this->em->getRepository(Order::class)->findBy(['user'=>$user->getIdProfil()], ['orderDate'=>'DESC']);

        return $this->render('checkout/userOrders.html.twig', ['orders' => $orders]);
    }

    #[Route('/orders/{idOrder}', name: 'route_orderDetails')]
    public function infoProduct($idOrder, Request $request, ManagerRegistry $doctrine): Response 
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $user = $this->getUser();

        $order = $this->em->getRepository(Order::class)->find($idOrder);

        if ($user->isThisMyId($order->getUserId())) {
            return $this->render('checkout/orderDetails.html.twig', ['order' => $order]);
        }
        
        return $this->redirectToRoute('route_userOrders');
    }
}

templates/checkout/orderDetails.html.twig
{% extends 'core/base.html.twig' %}

{% block title %}
	Dark Rosted Coffee
{% endblock %}

{% block content %}
	<div class="row page">
		<div class="col-10 mx-auto">
			{% for flash in app.flashes('stateUpdated') %}
				<div class="alert {{ flash.color }} notification mt-4">
					<i class="{{ flash.icon }}"></i>
					{{ flash.content }}</div>
			{% endfor %}
			<div class="col-12 d-flex justify-content-between mb-5">
				<h4 class="title-site">Order #{{ order.idOrder }}</h4>
				<h4 class="title-site">State:
					{{ order.state }}</h4>
				{% if is_granted("ROLE_ADMIN") %}
					{{ form_start(formStatus) }}
					{{ form_row(formStatus.state) }}
					{{ form_end(formStatus) }}
				{% endif %}

			</div>
			<div class="row col-12 user-details">
				<div class="col-5 row h-25">
					<div class="col-5 label">
						<ul>
							<li># Order</li>
							<li>Number of items</li>
							<li>Date of order</li>
							<li>Date of Delivery</li>
						</ul>
					</div>
					<div class="col-7">
						<ul>
							<li>{{ order.idOrder }}</li>
							<li>{{ order.getProducts() | length }}</li>
							<li>{{ order.orderDate | date("m/d/Y H:i", "America/Toronto") }}</li>
							<li>{% if order.deliveryDate == null %}To come
							{% else %}{{ order.deliveryDate | date("m/d/Y H:i", "America/Toronto") }}
								{% endif %}</li>
						</div>
					</div>
					<div class="col-4 row h-25">
						<div class="col-6 label">
							<ul>
								<li>Sub-Total</li>
								<li>Discount</li>
								<li>Delivery Fees</li>
								<li>Total(Taxes include)</li>
							</ul>
						</div>
						<div class="col-6">
							<ul>
								<li>{{ order.getSubtotal() }}$</li>
								<li>{{ order.getProducts() | length }}</li>
								<li>{{ order.deliveryFee }}</li>
								<li>{{ order.getTotalPrice() }}$</li>
							</ul>
						</div>
					</div>
					<div class="col-3 row h-25 d-flex justify-content-end">
						<ul>
							<li class="label">Delivery Address</li>
							<li>{{ order.user.firstName }}
								{{ order.user.lastName }}</li>
							<li>{{ order.user.address }},
								{{ order.user.town }},
								{{ order.user.postalCode }}</li>
						</ul>
					</div>
				</div>
				<div class="col-12 row">
					<table class="table text-center table-bordered">
						<thead class="table-dark">
							<tr>
								<th scope="col">Product</th>
								<th scope="col">Name</th>
								<th scope="col">Unit price</th>
								<th scope="col">Quantity</th>
								<th scope="col">Total</th>
							</tr>
						</thead>
						<tbody class="table-body">
							{% for purchase in order.getProducts() %}
								<tr>
									<td><img class="img-fluid img-product" src="{{ asset_if(purchase.product.imagePath, 'images/products/imageMissing.png') }}" alt="Image product"></td>
									<td>{{ purchase.product.name }}</td>
									<td>{{ purchase.product.price }}$</td>
									<td>{{ purchase.quantity }}</td>
									<td>{{ purchase.getTotal() }}$</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
					<div></div>
				</div>
			</div>
		</div>

	{% endblock %}

	{% block stylesheets %}
		<link rel="stylesheet" href="{{ asset('styles/orderDetails.css') }}">
		<link rel="stylesheet" href="{{ asset('styles/base.css') }}">
	{% endblock %}

	{% block javascripts %}
		<script src="{{ asset('scripts/order.detail.js') }}"></script>
	{% endblock %}

templates/checkout/orderReview.html.twig
{% extends 'core/base.html.twig' %}

{% block title %}
	Dark Rosted Coffee
{% endblock %}

{% block content %}

	<div class="row my-md-4 mx-xxl-5">
		<div class="col-md-8">
			<h3 class="title-site">Review your order</h3>
			<table class="table text-center table-bordered">
				<thead class="table-dark">
					<tr>
						<th scope="col">Product</th>
						<th scope="col">Name</th>
						<th scope="col">Unit price</th>
						<th scope="col">Quantity</th>
						<th scope="col">Total</th>
					</tr>
				</thead>
				<tbody class="table-body">
					{% for purchase in cart.items %}
						<tr>
							<td><img class="img-fluid img-product" src="{{ asset_if(purchase.product.imagePath, 'images/products/imageMissing.png') }}" alt="Image product"></td>
							<td>{{ purchase.product.name }}</td>
							<td>{{ purchase.product.price }}$</td>
							<td>{{ purchase.quantity }}</td>
							<td>{{ purchase.price * purchase.quantity }}$</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<div class="col-md-4 summary-table">
			<h3 class="title-site">Delivery informations</h3>
			<p>{{ user.lastName }} {{ user.firstName }}</p>
			<p>{{ user.email }}</p>
			<p>{{ user.address }}, {{ user.postalCode }}, {{ user.province }}</p>
			<table class="table">
				<thead>
					<tr>
						<th class="title-site">Summary</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Subtotal:
							{{ cart.getSubtotal() | number_format(2, '.',) }}$</td>
					</tr>
					<tr>
						<td>TPS:
							{{ cart.getTps() | number_format(2, '.',)}}$</td>
					</tr>
					<tr>
						<td>TVQ:
							{{ cart.getTvq() | number_format(2, '.',) }}$</td>
					</tr>
					<tr>
						<td>Delivery fees:
							{{ cart.getDeliveryFee() | number_format(2, '.',) }}$</td>
					</tr>
				</tbody>
			</table>
			<p>*Estimated total*</p>
			<a href="{{ path('stripe_chechout') }}">
				<button class="btnSite btn">
					<i class="fa-regular fa-credit-card">
						Order</i>
					-
					{{ cart.getTotal() | number_format(2, '.',) }}$</button>
			</a>
		</div>
	</div>
</div>
{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('styles/orderReview.css') }}">
	<link rel="stylesheet" href="{{ asset('styles/base.css') }}">
{% endblock %}

templates/checkout/userOrders.html.twig
{% extends 'core/base.html.twig' %}

{% block title %}
	Dark Rosted Coffee
{% endblock %}

{% block content %}
	<div class="row my-md-4 mx-xxl-5 page">
		<div class="col-10 mx-auto">
			{% for flash in app.flashes('order') %}
				<div class="alert {{ flash.color }} notification">{{ flash.content | raw }}</div>
			{% endfor %}
			<h3 class="title-site">Here are your orders</h3>
			{% if orders | length == 0 %}
				<h5>You have no orders to this date</h5>
			{% endif %}
			<table class="table text-center table-bordered">
				<thead class="table-dark">
					<tr>
						<th scope="col"># Order</th>
						<th scope="col">Date</th>
						<th scope="col">Total price</th>
						<th scope="col">Status</th>
						<th scope="col">Details</th>
					</tr>
				</thead>
				<tbody class="table-body">
					{% for order in orders %}
						<tr>
							<td>{{ order.idOrder }}</td>
							<td>{{ order.orderDate | date("m/d/Y H:i", "America/Toronto") }}</td>
							<td>{{ order.getTotalPrice() }}</td>
							<td>{{ order.state }}</td>
							{% if is_granted("ROLE_ADMIN") %}
								<td>
									<a href="{{ path('route_adminUpdateOrders', {idOrder: order.idOrder})}}">
										<i class="fas fa-eye"></i>
									</a>
								</td>
							{% else %}
								<td>
									<a href="{{ path('route_orderDetails', {idOrder: order.idOrder})}}">
										<i class="fas fa-eye"></i>
									</a>
								</td>
							{% endif %}
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('styles/orderReview.css') }}">
	<link rel="stylesheet" href="{{ asset('styles/base.css') }}">
{% endblock %}