src/Entity/Purchase.php
<?php

namespace App\Entity;

use App\Repository\PurchaseRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PurchaseRepository::class)]
#[ORM\Table(name:'purchases')]
class Purchase
{
    public function __construct($product)
    {
        // J'avais déjà la quantité dans mon constructeur
        $this->quantity = 1;
        $this->product = $product;
        $this->price = $product->getPrice();
    }

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name:'idPurchase')]
    private ?int $idPurchase = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?int $quantity = null;

    #[ORM\ManyToOne(inversedBy: 'purchases')]
    #[ORM\JoinColumn(nullable: false, name:'idOrder', referencedColumnName:'idOrder')]
    private ?Order $orderRelated = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false, name:'idProduct', referencedColumnName:'idProduct')]
    private ?Product $product = null;

    public function getIdPurchase(): ?int
    {
        return $this->idPurchase;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getOrderRelated(): ?Order
    {
        return $this->orderRelated;
    }

    public function setOrderRelated(?Order $orderRelated): self
    {
        $this->orderRelated = $orderRelated;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function getTotal(){
        return $this->price * $this->quantity;
    }

    public function decrementQuantityInStock() {
        $this->product->decrementQuantityInStock($this->quantity);
    }

    public function getQuantityInStock() {
        return $this->product->getQuantityInStock();
    }

    public function getProductName() {
        return $this->product->getName();
    }
}

src/Controller/CatalogueController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Product;
use Doctrine\Persistence\ManagerRegistry;
use SebastianBergmann\Environment\Console;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class CatalogueController extends AbstractController
{
    private $session;
    private $em = null;

    #[Route('/', name: 'route_catalogue')]
    public function indexRoute(Request $request, ManagerRegistry $doctrine): Response
    {
        $this->em = $doctrine->getManager();
        $session = $request->getSession();

        $category = $request->query->get('category');
        $searchField = $request->request->get('search_field');

        $categories = $this->retreiveAllCategories();
        $products = $this->retreiveProduct($category, $searchField);

        return $this->render('catalogue/catalogue.html.twig', [
            'products' => $products, 
            'categories' => $categories, 
            'cart'=> $session->get('cart')
        ]);
    }

    #[Route('/products/{idProduct}', name: 'product-modal')]
    public function infoProduct($idProduct, Request $request, ManagerRegistry $doctrine): Response
    {
        $this->em = $doctrine->getManager();

        $product = $this->em->getRepository(Product::class)->find($idProduct);

        return $this->render('catalogue/product.modal.twig', ['product' => $product]);
    }

    private function retreiveAllCategories()
    {
        return $this->em->getRepository(Category::class)->findAll();
    }

    private function retreiveProduct($category, $searchField)
    {
        return $this->em->getRepository(Product::class)->findWithCriteria($category, $searchField);
    }
}

templates/catalogue/catalogue.html.twig
{% extends 'core/base.html.twig' %}

{% block title %}
	Dark Rosted Coffee
{% endblock %}

{% block content %}
	<div class="row mb-5 body">

		{# Left - Type list #}
		<div class="col-xxl-2 col-md-4 row side-bar px-md-5">
			<ul>
				<a href="{{path('route_catalogue') }}">
					<li>All</li>
				</a>
				{% for category in categories %}
					<a href="{{ path('route_catalogue' , { category: category.idCategory }) }}">
						<li>{{ category.category }}
							-
							{{ category.getProducts() | length }}</li>
					</a>
				{% endfor %}
			</ul>
		</div>

		{# Products #}
		<div class="col-xxl-10 col-md-8">
			<div
				class="row">
				{# Top - Product type #}
				<h2 class="title-site mt-3 mb-3">
					Our products - ({{products | length}})
				</h2>
				{% if products | length > 0 %}
					{% for product in products %}
						<div
							class="m-md-3 mb-3 col-xxl-3 col-md-5 card card-modal">
							{# Section card #}
							<div>
								<a class="product-modal text-center align-self-center " href="{{ path('product-modal', {idProduct: product.idProduct})}}">
									<div
										class="card-header">
										{# Card title #}
										<h5 class="card-title text-center">{{ product.name }}</h5>
									</div>
									{# Product image #}
									<div class="card-body">
										<img class="img-fluid" src="{{ asset_if(product.imagePath, 'images/products/imageMissing.png') }}" alt="Image product">
									</div>
								</a>
							</div>
							<div
								class="card-footer">
								{# Price #}
								<div class="m-2 text-center">
									<span>{{ product.price | number_format(2, '.',)}}$</span>/each
								</div>
								{# Buy button && View button #}
								<div class="row icons">
									<div class="col-6">
										<a href="{{ path('add_purchase', {idProduct: product.idProduct})}}">
											<i class="fa-solid fa-cart-plus btn-purchase"></i>
										</a>
									</div>
									<a class="product-modal col-6 align-self-center text-end" href="{{ path('product-modal', {idProduct: product.idProduct})}}">
										<i class="fa-solid fa-circle-info"></i>
									</a>
								</div>
							</div>
						</div>
					{% endfor %}

					{# Section no available products #}
				{% else %}
					<div>
						<p>Sorry, no products are available in this categorie.</p>
					</div>
				{% endif %}
			</div>
		</div>
	</div>

	{# Section modal products #}
	<div class="modal fade" tabindex="-1" id="product-modal">
		<div class="modal-dialog modal-lg">
			<div id="product-modal-content" class="modal-content"></div>
		</div>
	</div>
{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('styles/catalogue.css') }}">
	<link rel="stylesheet" href="{{ asset('styles/modal.css') }}">
	<link rel="stylesheet" href="{{ asset('styles/base.css') }}">
{% endblock %}

{% block javascripts %}
	<script src="{{ asset('scripts/modal.product.js') }}"></script>
{% endblock %}

templates/catalogue/product.modal.twig
{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('styles/modal.css') }}">
{% endblock %}

<div class="modal-header">
	<h5 class="modal-title">{{ product.name }}</h5>
	<button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
	<div class="row">
		<div class="col-6">
			<img class="img-fluid" src="{{ asset_if(product.imagePath, 'images/products/imageMissing.png') }}" alt="Image product">
		</div>
		<div class="col-6">
			<p><span>Category:</span> {{ product.mainCategory.category }}</p>
			<hr>
			<p><span>Description:</span><br>
				{{ product.description }}
			</p>
		</div>
		<div class="text-center align-content-center col-12 row">
			<div class="col-6">
					<span>Price:</span>
					<span class="infos-font">{{ product.price | number_format(2, '.',)}}$</span>/each.
			</div>
			<div class="col-6">
					<span>Quantity in stock:</span>
					<span class="infos-font">{{ product.quantityInStock}}</span>
			</div>
		</div>
	</div>
</div>
<div class="modal-footer">
	<a href="{{ path('add_purchase', {idProduct: product.idProduct}) }}"><button type="button" class="btn btn-secondary">Add to basket <i class="fa-solid fa-cart-plus"></i></button></a>
	<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
</div>